//
// @author: jiahong
// @date  : 20/05/18 3:17 PM
//

#include <algorithm>
#include <iostream>

#include "romania.h"
#include "string_ops.h"

void
aima::Romania::setup() {
    add("Oradea", "Zerind", 71);
    add("Oradea", "Sibiu", 151);
    add("Zerind", "Arad", 75);
    add("Arad", "Sibiu", 140);
    add("Arad", "Timisoara", 118);
    add("Timisoara", "Lugoj", 111);
    add("Lugoj", "Mehadia", 70);
    add("Mehadia", "Drobeta", 75);
    add("Drobeta", "Craiova", 120);
    add("Craiova", "Rimnicu Vilcea", 146);
    add("Craiova", "Pitesti", 138);
    add("Sibiu", "Fagaras", 99);
    add("Sibiu", "Rimnicu Vilcea", 80);
    add("Rimnicu Vilcea", "Pitesti", 87);
    add("Fagaras", "Bucharest", 211);
    add("Pitesti", "Bucharest", 101);
    add("Bucharest", "Giurgiu", 90);
    add("Bucharest", "Urziceni", 85);
    add("Urziceni", "Hirsova", 98);
    add("Urziceni", "Vaslui", 142);
    add("Hirsova", "Eforie", 86);
    add("Vaslui", "Iasi", 92);
    add("Iasi", "Neami", 87);
}

std::vector<std::string>
aima::RomaniaMap::actions(const aima::Romania &state) const {
    auto neighbours = romania_.neighbours(state.whereami());
    std::vector<std::string> actions;
    // extract weights from the pairs (we don't need them)
    std::transform(neighbours.cbegin(),
                   neighbours.cend(),
                   std::back_inserter(actions),
                   [](auto pair) {
        return pair.first;
    });
    return actions;
}

aima::Romania
aima::RomaniaMap::successor(const aima::Romania &state, const std::string &action) const {
    auto child = state;
    child.advance(action);
    return child;
}

std::ostream
&aima::operator<<(std::ostream &os, const aima::Romania &romania) {
    return os << aima::join(romania.path_.cbegin(), romania.path_.cend(), " -> ");
}

void
aima::Romania::build_heuristics() {
    add_LB_estimate("Neami", "Iasi", 86.5);
    add_LB_estimate("Neami", "Eforie", 504.5);
    add_LB_estimate("Neami", "Lugoj", 909.5);
    add_LB_estimate("Neami", "Oradea", 824.5);
    add_LB_estimate("Neami", "Craiova", 644.5);
    add_LB_estimate("Neami", "Arad", 813.5);
    add_LB_estimate("Neami", "Sibiu", 673.5);
    add_LB_estimate("Neami", "Zerind", 888.5);
    add_LB_estimate("Neami", "Mehadia", 839.5);
    add_LB_estimate("Neami", "Fagaras", 616.5);
    add_LB_estimate("Neami", "Drobeta", 764.5);
    add_LB_estimate("Neami", "Rimnicu Vilcea", 593.5);
    add_LB_estimate("Neami", "Pitesti", 506.5);
    add_LB_estimate("Neami", "Bucharest", 405.5);
    add_LB_estimate("Neami", "Urziceni", 320.5);
    add_LB_estimate("Neami", "Vaslui", 178.5);
    add_LB_estimate("Neami", "Timisoara", 931.5);
    add_LB_estimate("Neami", "Hirsova", 418.5);
    add_LB_estimate("Neami", "Giurgiu", 495.5);
    add_LB_estimate("Iasi", "Neami", 86.5);
    add_LB_estimate("Iasi", "Eforie", 417.5);
    add_LB_estimate("Iasi", "Lugoj", 822.5);
    add_LB_estimate("Iasi", "Oradea", 737.5);
    add_LB_estimate("Iasi", "Craiova", 557.5);
    add_LB_estimate("Iasi", "Arad", 726.5);
    add_LB_estimate("Iasi", "Sibiu", 586.5);
    add_LB_estimate("Iasi", "Zerind", 801.5);
    add_LB_estimate("Iasi", "Mehadia", 752.5);
    add_LB_estimate("Iasi", "Fagaras", 529.5);
    add_LB_estimate("Iasi", "Drobeta", 677.5);
    add_LB_estimate("Iasi", "Rimnicu Vilcea", 506.5);
    add_LB_estimate("Iasi", "Pitesti", 419.5);
    add_LB_estimate("Iasi", "Bucharest", 318.5);
    add_LB_estimate("Iasi", "Urziceni", 233.5);
    add_LB_estimate("Iasi", "Vaslui", 91.5);
    add_LB_estimate("Iasi", "Timisoara", 844.5);
    add_LB_estimate("Iasi", "Hirsova", 331.5);
    add_LB_estimate("Iasi", "Giurgiu", 408.5);
    add_LB_estimate("Eforie", "Neami", 504.5);
    add_LB_estimate("Eforie", "Iasi", 417.5);
    add_LB_estimate("Eforie", "Lugoj", 772.5);
    add_LB_estimate("Eforie", "Oradea", 687.5);
    add_LB_estimate("Eforie", "Craiova", 507.5);
    add_LB_estimate("Eforie", "Arad", 676.5);
    add_LB_estimate("Eforie", "Sibiu", 536.5);
    add_LB_estimate("Eforie", "Zerind", 751.5);
    add_LB_estimate("Eforie", "Mehadia", 702.5);
    add_LB_estimate("Eforie", "Fagaras", 479.5);
    add_LB_estimate("Eforie", "Drobeta", 627.5);
    add_LB_estimate("Eforie", "Rimnicu Vilcea", 456.5);
    add_LB_estimate("Eforie", "Pitesti", 369.5);
    add_LB_estimate("Eforie", "Bucharest", 268.5);
    add_LB_estimate("Eforie", "Urziceni", 183.5);
    add_LB_estimate("Eforie", "Vaslui", 325.5);
    add_LB_estimate("Eforie", "Timisoara", 794.5);
    add_LB_estimate("Eforie", "Hirsova", 85.5);
    add_LB_estimate("Eforie", "Giurgiu", 358.5);
    add_LB_estimate("Lugoj", "Neami", 909.5);
    add_LB_estimate("Lugoj", "Iasi", 822.5);
    add_LB_estimate("Lugoj", "Eforie", 772.5);
    add_LB_estimate("Lugoj", "Oradea", 374.5);
    add_LB_estimate("Lugoj", "Craiova", 264.5);
    add_LB_estimate("Lugoj", "Arad", 228.5);
    add_LB_estimate("Lugoj", "Sibiu", 368.5);
    add_LB_estimate("Lugoj", "Zerind", 303.5);
    add_LB_estimate("Lugoj", "Mehadia", 69.5);
    add_LB_estimate("Lugoj", "Fagaras", 467.5);
    add_LB_estimate("Lugoj", "Drobeta", 144.5);
    add_LB_estimate("Lugoj", "Rimnicu Vilcea", 410.5);
    add_LB_estimate("Lugoj", "Pitesti", 402.5);
    add_LB_estimate("Lugoj", "Bucharest", 503.5);
    add_LB_estimate("Lugoj", "Urziceni", 588.5);
    add_LB_estimate("Lugoj", "Vaslui", 730.5);
    add_LB_estimate("Lugoj", "Timisoara", 110.5);
    add_LB_estimate("Lugoj", "Hirsova", 686.5);
    add_LB_estimate("Lugoj", "Giurgiu", 593.5);
    add_LB_estimate("Oradea", "Neami", 824.5);
    add_LB_estimate("Oradea", "Iasi", 737.5);
    add_LB_estimate("Oradea", "Eforie", 687.5);
    add_LB_estimate("Oradea", "Lugoj", 374.5);
    add_LB_estimate("Oradea", "Craiova", 376.5);
    add_LB_estimate("Oradea", "Arad", 145.5);
    add_LB_estimate("Oradea", "Sibiu", 150.5);
    add_LB_estimate("Oradea", "Zerind", 70.5);
    add_LB_estimate("Oradea", "Mehadia", 444.5);
    add_LB_estimate("Oradea", "Fagaras", 249.5);
    add_LB_estimate("Oradea", "Drobeta", 496.5);
    add_LB_estimate("Oradea", "Rimnicu Vilcea", 230.5);
    add_LB_estimate("Oradea", "Pitesti", 317.5);
    add_LB_estimate("Oradea", "Bucharest", 418.5);
    add_LB_estimate("Oradea", "Urziceni", 503.5);
    add_LB_estimate("Oradea", "Vaslui", 645.5);
    add_LB_estimate("Oradea", "Timisoara", 263.5);
    add_LB_estimate("Oradea", "Hirsova", 601.5);
    add_LB_estimate("Oradea", "Giurgiu", 508.5);
    add_LB_estimate("Craiova", "Neami", 644.5);
    add_LB_estimate("Craiova", "Iasi", 557.5);
    add_LB_estimate("Craiova", "Eforie", 507.5);
    add_LB_estimate("Craiova", "Lugoj", 264.5);
    add_LB_estimate("Craiova", "Oradea", 376.5);
    add_LB_estimate("Craiova", "Arad", 365.5);
    add_LB_estimate("Craiova", "Sibiu", 225.5);
    add_LB_estimate("Craiova", "Zerind", 440.5);
    add_LB_estimate("Craiova", "Mehadia", 194.5);
    add_LB_estimate("Craiova", "Fagaras", 324.5);
    add_LB_estimate("Craiova", "Drobeta", 119.5);
    add_LB_estimate("Craiova", "Rimnicu Vilcea", 145.5);
    add_LB_estimate("Craiova", "Pitesti", 137.5);
    add_LB_estimate("Craiova", "Bucharest", 238.5);
    add_LB_estimate("Craiova", "Urziceni", 323.5);
    add_LB_estimate("Craiova", "Vaslui", 465.5);
    add_LB_estimate("Craiova", "Timisoara", 375.5);
    add_LB_estimate("Craiova", "Hirsova", 421.5);
    add_LB_estimate("Craiova", "Giurgiu", 328.5);
    add_LB_estimate("Arad", "Neami", 813.5);
    add_LB_estimate("Arad", "Iasi", 726.5);
    add_LB_estimate("Arad", "Eforie", 676.5);
    add_LB_estimate("Arad", "Lugoj", 228.5);
    add_LB_estimate("Arad", "Oradea", 145.5);
    add_LB_estimate("Arad", "Craiova", 365.5);
    add_LB_estimate("Arad", "Sibiu", 139.5);
    add_LB_estimate("Arad", "Zerind", 74.5);
    add_LB_estimate("Arad", "Mehadia", 298.5);
    add_LB_estimate("Arad", "Fagaras", 238.5);
    add_LB_estimate("Arad", "Drobeta", 373.5);
    add_LB_estimate("Arad", "Rimnicu Vilcea", 219.5);
    add_LB_estimate("Arad", "Pitesti", 306.5);
    add_LB_estimate("Arad", "Bucharest", 407.5);
    add_LB_estimate("Arad", "Urziceni", 492.5);
    add_LB_estimate("Arad", "Vaslui", 634.5);
    add_LB_estimate("Arad", "Timisoara", 117.5);
    add_LB_estimate("Arad", "Hirsova", 590.5);
    add_LB_estimate("Arad", "Giurgiu", 497.5);
    add_LB_estimate("Sibiu", "Neami", 673.5);
    add_LB_estimate("Sibiu", "Iasi", 586.5);
    add_LB_estimate("Sibiu", "Eforie", 536.5);
    add_LB_estimate("Sibiu", "Lugoj", 368.5);
    add_LB_estimate("Sibiu", "Oradea", 150.5);
    add_LB_estimate("Sibiu", "Craiova", 225.5);
    add_LB_estimate("Sibiu", "Arad", 139.5);
    add_LB_estimate("Sibiu", "Zerind", 214.5);
    add_LB_estimate("Sibiu", "Mehadia", 420.5);
    add_LB_estimate("Sibiu", "Fagaras", 98.5);
    add_LB_estimate("Sibiu", "Drobeta", 345.5);
    add_LB_estimate("Sibiu", "Rimnicu Vilcea", 79.5);
    add_LB_estimate("Sibiu", "Pitesti", 166.5);
    add_LB_estimate("Sibiu", "Bucharest", 267.5);
    add_LB_estimate("Sibiu", "Urziceni", 352.5);
    add_LB_estimate("Sibiu", "Vaslui", 494.5);
    add_LB_estimate("Sibiu", "Timisoara", 257.5);
    add_LB_estimate("Sibiu", "Hirsova", 450.5);
    add_LB_estimate("Sibiu", "Giurgiu", 357.5);
    add_LB_estimate("Zerind", "Neami", 888.5);
    add_LB_estimate("Zerind", "Iasi", 801.5);
    add_LB_estimate("Zerind", "Eforie", 751.5);
    add_LB_estimate("Zerind", "Lugoj", 303.5);
    add_LB_estimate("Zerind", "Oradea", 70.5);
    add_LB_estimate("Zerind", "Craiova", 440.5);
    add_LB_estimate("Zerind", "Arad", 74.5);
    add_LB_estimate("Zerind", "Sibiu", 214.5);
    add_LB_estimate("Zerind", "Mehadia", 373.5);
    add_LB_estimate("Zerind", "Fagaras", 313.5);
    add_LB_estimate("Zerind", "Drobeta", 448.5);
    add_LB_estimate("Zerind", "Rimnicu Vilcea", 294.5);
    add_LB_estimate("Zerind", "Pitesti", 381.5);
    add_LB_estimate("Zerind", "Bucharest", 482.5);
    add_LB_estimate("Zerind", "Urziceni", 567.5);
    add_LB_estimate("Zerind", "Vaslui", 709.5);
    add_LB_estimate("Zerind", "Timisoara", 192.5);
    add_LB_estimate("Zerind", "Hirsova", 665.5);
    add_LB_estimate("Zerind", "Giurgiu", 572.5);
    add_LB_estimate("Mehadia", "Neami", 839.5);
    add_LB_estimate("Mehadia", "Iasi", 752.5);
    add_LB_estimate("Mehadia", "Eforie", 702.5);
    add_LB_estimate("Mehadia", "Lugoj", 69.5);
    add_LB_estimate("Mehadia", "Oradea", 444.5);
    add_LB_estimate("Mehadia", "Craiova", 194.5);
    add_LB_estimate("Mehadia", "Arad", 298.5);
    add_LB_estimate("Mehadia", "Sibiu", 420.5);
    add_LB_estimate("Mehadia", "Zerind", 373.5);
    add_LB_estimate("Mehadia", "Fagaras", 519.5);
    add_LB_estimate("Mehadia", "Drobeta", 74.5);
    add_LB_estimate("Mehadia", "Rimnicu Vilcea", 340.5);
    add_LB_estimate("Mehadia", "Pitesti", 332.5);
    add_LB_estimate("Mehadia", "Bucharest", 433.5);
    add_LB_estimate("Mehadia", "Urziceni", 518.5);
    add_LB_estimate("Mehadia", "Vaslui", 660.5);
    add_LB_estimate("Mehadia", "Timisoara", 180.5);
    add_LB_estimate("Mehadia", "Hirsova", 616.5);
    add_LB_estimate("Mehadia", "Giurgiu", 523.5);
    add_LB_estimate("Fagaras", "Neami", 616.5);
    add_LB_estimate("Fagaras", "Iasi", 529.5);
    add_LB_estimate("Fagaras", "Eforie", 479.5);
    add_LB_estimate("Fagaras", "Lugoj", 467.5);
    add_LB_estimate("Fagaras", "Oradea", 249.5);
    add_LB_estimate("Fagaras", "Craiova", 324.5);
    add_LB_estimate("Fagaras", "Arad", 238.5);
    add_LB_estimate("Fagaras", "Sibiu", 98.5);
    add_LB_estimate("Fagaras", "Zerind", 313.5);
    add_LB_estimate("Fagaras", "Mehadia", 519.5);
    add_LB_estimate("Fagaras", "Drobeta", 444.5);
    add_LB_estimate("Fagaras", "Rimnicu Vilcea", 178.5);
    add_LB_estimate("Fagaras", "Pitesti", 265.5);
    add_LB_estimate("Fagaras", "Bucharest", 210.5);
    add_LB_estimate("Fagaras", "Urziceni", 295.5);
    add_LB_estimate("Fagaras", "Vaslui", 437.5);
    add_LB_estimate("Fagaras", "Timisoara", 356.5);
    add_LB_estimate("Fagaras", "Hirsova", 393.5);
    add_LB_estimate("Fagaras", "Giurgiu", 300.5);
    add_LB_estimate("Drobeta", "Neami", 764.5);
    add_LB_estimate("Drobeta", "Iasi", 677.5);
    add_LB_estimate("Drobeta", "Eforie", 627.5);
    add_LB_estimate("Drobeta", "Lugoj", 144.5);
    add_LB_estimate("Drobeta", "Oradea", 496.5);
    add_LB_estimate("Drobeta", "Craiova", 119.5);
    add_LB_estimate("Drobeta", "Arad", 373.5);
    add_LB_estimate("Drobeta", "Sibiu", 345.5);
    add_LB_estimate("Drobeta", "Zerind", 448.5);
    add_LB_estimate("Drobeta", "Mehadia", 74.5);
    add_LB_estimate("Drobeta", "Fagaras", 444.5);
    add_LB_estimate("Drobeta", "Rimnicu Vilcea", 265.5);
    add_LB_estimate("Drobeta", "Pitesti", 257.5);
    add_LB_estimate("Drobeta", "Bucharest", 358.5);
    add_LB_estimate("Drobeta", "Urziceni", 443.5);
    add_LB_estimate("Drobeta", "Vaslui", 585.5);
    add_LB_estimate("Drobeta", "Timisoara", 255.5);
    add_LB_estimate("Drobeta", "Hirsova", 541.5);
    add_LB_estimate("Drobeta", "Giurgiu", 448.5);
    add_LB_estimate("Rimnicu Vilcea", "Neami", 593.5);
    add_LB_estimate("Rimnicu Vilcea", "Iasi", 506.5);
    add_LB_estimate("Rimnicu Vilcea", "Eforie", 456.5);
    add_LB_estimate("Rimnicu Vilcea", "Lugoj", 410.5);
    add_LB_estimate("Rimnicu Vilcea", "Oradea", 230.5);
    add_LB_estimate("Rimnicu Vilcea", "Craiova", 145.5);
    add_LB_estimate("Rimnicu Vilcea", "Arad", 219.5);
    add_LB_estimate("Rimnicu Vilcea", "Sibiu", 79.5);
    add_LB_estimate("Rimnicu Vilcea", "Zerind", 294.5);
    add_LB_estimate("Rimnicu Vilcea", "Mehadia", 340.5);
    add_LB_estimate("Rimnicu Vilcea", "Fagaras", 178.5);
    add_LB_estimate("Rimnicu Vilcea", "Drobeta", 265.5);
    add_LB_estimate("Rimnicu Vilcea", "Pitesti", 86.5);
    add_LB_estimate("Rimnicu Vilcea", "Bucharest", 187.5);
    add_LB_estimate("Rimnicu Vilcea", "Urziceni", 272.5);
    add_LB_estimate("Rimnicu Vilcea", "Vaslui", 414.5);
    add_LB_estimate("Rimnicu Vilcea", "Timisoara", 337.5);
    add_LB_estimate("Rimnicu Vilcea", "Hirsova", 370.5);
    add_LB_estimate("Rimnicu Vilcea", "Giurgiu", 277.5);
    add_LB_estimate("Pitesti", "Neami", 506.5);
    add_LB_estimate("Pitesti", "Iasi", 419.5);
    add_LB_estimate("Pitesti", "Eforie", 369.5);
    add_LB_estimate("Pitesti", "Lugoj", 402.5);
    add_LB_estimate("Pitesti", "Oradea", 317.5);
    add_LB_estimate("Pitesti", "Craiova", 137.5);
    add_LB_estimate("Pitesti", "Arad", 306.5);
    add_LB_estimate("Pitesti", "Sibiu", 166.5);
    add_LB_estimate("Pitesti", "Zerind", 381.5);
    add_LB_estimate("Pitesti", "Mehadia", 332.5);
    add_LB_estimate("Pitesti", "Fagaras", 265.5);
    add_LB_estimate("Pitesti", "Drobeta", 257.5);
    add_LB_estimate("Pitesti", "Rimnicu Vilcea", 86.5);
    add_LB_estimate("Pitesti", "Bucharest", 100.5);
    add_LB_estimate("Pitesti", "Urziceni", 185.5);
    add_LB_estimate("Pitesti", "Vaslui", 327.5);
    add_LB_estimate("Pitesti", "Timisoara", 424.5);
    add_LB_estimate("Pitesti", "Hirsova", 283.5);
    add_LB_estimate("Pitesti", "Giurgiu", 190.5);
    add_LB_estimate("Bucharest", "Neami", 405.5);
    add_LB_estimate("Bucharest", "Iasi", 318.5);
    add_LB_estimate("Bucharest", "Eforie", 268.5);
    add_LB_estimate("Bucharest", "Lugoj", 503.5);
    add_LB_estimate("Bucharest", "Oradea", 418.5);
    add_LB_estimate("Bucharest", "Craiova", 238.5);
    add_LB_estimate("Bucharest", "Arad", 407.5);
    add_LB_estimate("Bucharest", "Sibiu", 267.5);
    add_LB_estimate("Bucharest", "Zerind", 482.5);
    add_LB_estimate("Bucharest", "Mehadia", 433.5);
    add_LB_estimate("Bucharest", "Fagaras", 210.5);
    add_LB_estimate("Bucharest", "Drobeta", 358.5);
    add_LB_estimate("Bucharest", "Rimnicu Vilcea", 187.5);
    add_LB_estimate("Bucharest", "Pitesti", 100.5);
    add_LB_estimate("Bucharest", "Urziceni", 84.5);
    add_LB_estimate("Bucharest", "Vaslui", 226.5);
    add_LB_estimate("Bucharest", "Timisoara", 525.5);
    add_LB_estimate("Bucharest", "Hirsova", 182.5);
    add_LB_estimate("Bucharest", "Giurgiu", 89.5);
    add_LB_estimate("Urziceni", "Neami", 320.5);
    add_LB_estimate("Urziceni", "Iasi", 233.5);
    add_LB_estimate("Urziceni", "Eforie", 183.5);
    add_LB_estimate("Urziceni", "Lugoj", 588.5);
    add_LB_estimate("Urziceni", "Oradea", 503.5);
    add_LB_estimate("Urziceni", "Craiova", 323.5);
    add_LB_estimate("Urziceni", "Arad", 492.5);
    add_LB_estimate("Urziceni", "Sibiu", 352.5);
    add_LB_estimate("Urziceni", "Zerind", 567.5);
    add_LB_estimate("Urziceni", "Mehadia", 518.5);
    add_LB_estimate("Urziceni", "Fagaras", 295.5);
    add_LB_estimate("Urziceni", "Drobeta", 443.5);
    add_LB_estimate("Urziceni", "Rimnicu Vilcea", 272.5);
    add_LB_estimate("Urziceni", "Pitesti", 185.5);
    add_LB_estimate("Urziceni", "Bucharest", 84.5);
    add_LB_estimate("Urziceni", "Vaslui", 141.5);
    add_LB_estimate("Urziceni", "Timisoara", 610.5);
    add_LB_estimate("Urziceni", "Hirsova", 97.5);
    add_LB_estimate("Urziceni", "Giurgiu", 174.5);
    add_LB_estimate("Vaslui", "Neami", 178.5);
    add_LB_estimate("Vaslui", "Iasi", 91.5);
    add_LB_estimate("Vaslui", "Eforie", 325.5);
    add_LB_estimate("Vaslui", "Lugoj", 730.5);
    add_LB_estimate("Vaslui", "Oradea", 645.5);
    add_LB_estimate("Vaslui", "Craiova", 465.5);
    add_LB_estimate("Vaslui", "Arad", 634.5);
    add_LB_estimate("Vaslui", "Sibiu", 494.5);
    add_LB_estimate("Vaslui", "Zerind", 709.5);
    add_LB_estimate("Vaslui", "Mehadia", 660.5);
    add_LB_estimate("Vaslui", "Fagaras", 437.5);
    add_LB_estimate("Vaslui", "Drobeta", 585.5);
    add_LB_estimate("Vaslui", "Rimnicu Vilcea", 414.5);
    add_LB_estimate("Vaslui", "Pitesti", 327.5);
    add_LB_estimate("Vaslui", "Bucharest", 226.5);
    add_LB_estimate("Vaslui", "Urziceni", 141.5);
    add_LB_estimate("Vaslui", "Timisoara", 752.5);
    add_LB_estimate("Vaslui", "Hirsova", 239.5);
    add_LB_estimate("Vaslui", "Giurgiu", 316.5);
    add_LB_estimate("Timisoara", "Neami", 931.5);
    add_LB_estimate("Timisoara", "Iasi", 844.5);
    add_LB_estimate("Timisoara", "Eforie", 794.5);
    add_LB_estimate("Timisoara", "Lugoj", 110.5);
    add_LB_estimate("Timisoara", "Oradea", 263.5);
    add_LB_estimate("Timisoara", "Craiova", 375.5);
    add_LB_estimate("Timisoara", "Arad", 117.5);
    add_LB_estimate("Timisoara", "Sibiu", 257.5);
    add_LB_estimate("Timisoara", "Zerind", 192.5);
    add_LB_estimate("Timisoara", "Mehadia", 180.5);
    add_LB_estimate("Timisoara", "Fagaras", 356.5);
    add_LB_estimate("Timisoara", "Drobeta", 255.5);
    add_LB_estimate("Timisoara", "Rimnicu Vilcea", 337.5);
    add_LB_estimate("Timisoara", "Pitesti", 424.5);
    add_LB_estimate("Timisoara", "Bucharest", 525.5);
    add_LB_estimate("Timisoara", "Urziceni", 610.5);
    add_LB_estimate("Timisoara", "Vaslui", 752.5);
    add_LB_estimate("Timisoara", "Hirsova", 708.5);
    add_LB_estimate("Timisoara", "Giurgiu", 615.5);
    add_LB_estimate("Hirsova", "Neami", 418.5);
    add_LB_estimate("Hirsova", "Iasi", 331.5);
    add_LB_estimate("Hirsova", "Eforie", 85.5);
    add_LB_estimate("Hirsova", "Lugoj", 686.5);
    add_LB_estimate("Hirsova", "Oradea", 601.5);
    add_LB_estimate("Hirsova", "Craiova", 421.5);
    add_LB_estimate("Hirsova", "Arad", 590.5);
    add_LB_estimate("Hirsova", "Sibiu", 450.5);
    add_LB_estimate("Hirsova", "Zerind", 665.5);
    add_LB_estimate("Hirsova", "Mehadia", 616.5);
    add_LB_estimate("Hirsova", "Fagaras", 393.5);
    add_LB_estimate("Hirsova", "Drobeta", 541.5);
    add_LB_estimate("Hirsova", "Rimnicu Vilcea", 370.5);
    add_LB_estimate("Hirsova", "Pitesti", 283.5);
    add_LB_estimate("Hirsova", "Bucharest", 182.5);
    add_LB_estimate("Hirsova", "Urziceni", 97.5);
    add_LB_estimate("Hirsova", "Vaslui", 239.5);
    add_LB_estimate("Hirsova", "Timisoara", 708.5);
    add_LB_estimate("Hirsova", "Giurgiu", 272.5);
    add_LB_estimate("Giurgiu", "Neami", 495.5);
    add_LB_estimate("Giurgiu", "Iasi", 408.5);
    add_LB_estimate("Giurgiu", "Eforie", 358.5);
    add_LB_estimate("Giurgiu", "Lugoj", 593.5);
    add_LB_estimate("Giurgiu", "Oradea", 508.5);
    add_LB_estimate("Giurgiu", "Craiova", 328.5);
    add_LB_estimate("Giurgiu", "Arad", 497.5);
    add_LB_estimate("Giurgiu", "Sibiu", 357.5);
    add_LB_estimate("Giurgiu", "Zerind", 572.5);
    add_LB_estimate("Giurgiu", "Mehadia", 523.5);
    add_LB_estimate("Giurgiu", "Fagaras", 300.5);
    add_LB_estimate("Giurgiu", "Drobeta", 448.5);
    add_LB_estimate("Giurgiu", "Rimnicu Vilcea", 277.5);
    add_LB_estimate("Giurgiu", "Pitesti", 190.5);
    add_LB_estimate("Giurgiu", "Bucharest", 89.5);
    add_LB_estimate("Giurgiu", "Urziceni", 174.5);
    add_LB_estimate("Giurgiu", "Vaslui", 316.5);
    add_LB_estimate("Giurgiu", "Timisoara", 615.5);
    add_LB_estimate("Giurgiu", "Hirsova", 272.5);
}

void
aima::Romania::add_LB_estimate(const std::string &from, const std::string &to, double guess) {
    heuristics_[from + to] = guess;
}


