language: cpp
compiler: gcc
dist: trusty

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install: 
    - sudo apt-get install -qq g++-7 valgrind
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - g++ --version

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - pwd
    - make
    - ctest
    - ctest -T memcheck
